name: Save History

on:
  schedule:
    - cron: '00 19 * * *'   # 11:00 PM IST
  workflow_dispatch:

jobs:
  save-history:
    runs-on: ubuntu-latest

    steps:
      - name: Save Results
        run: |

          TODAY=$(TZ='Asia/Kolkata' date -d "yesterday" +%F)

          # Purane records delete karo (same date ke)
          curl -X DELETE "${{ secrets.SUPABASE_URL }}/rest/v1/results?result_date=eq.$TODAY" \
          -H "apikey: ${{ secrets.SUPABASE_SERVICE_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_KEY }}" \
          -H "Prefer: return=minimal"

          # Number table read karo
          DATA=$(curl -s "${{ secrets.SUPABASE_URL }}/rest/v1/number?select=slot,number" \
          -H "apikey: ${{ secrets.SUPABASE_SERVICE_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_KEY }}")

          N12=$(echo "$DATA" | jq '.[] | select(.slot=="12PM") | .number')
          N14=$(echo "$DATA" | jq '.[] | select(.slot=="2PM") | .number')
          N16=$(echo "$DATA" | jq '.[] | select(.slot=="4PM") | .number')
          N18=$(echo "$DATA" | jq '.[] | select(.slot=="6PM") | .number')
          N20=$(echo "$DATA" | jq '.[] | select(.slot=="8PM") | .number')
          N22=$(echo "$DATA" | jq '.[] | select(.slot=="10PM") | .number')

          # Results table save karo
          curl -X POST "${{ secrets.SUPABASE_URL }}/rest/v1/results" \
          -H "apikey: ${{ secrets.SUPABASE_SERVICE_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_KEY }}" \
          -H "Content-Type: application/json" \
          -d "[
          {\"result_date\":\"$TODAY\",\"slot\":\"12PM\",\"number\":$N12},
          {\"result_date\":\"$TODAY\",\"slot\":\"2PM\",\"number\":$N14},
          {\"result_date\":\"$TODAY\",\"slot\":\"4PM\",\"number\":$N16},
          {\"result_date\":\"$TODAY\",\"slot\":\"6PM\",\"number\":$N18},
          {\"result_date\":\"$TODAY\",\"slot\":\"8PM\",\"number\":$N20},
          {\"result_date\":\"$TODAY\",\"slot\":\"10PM\",\"number\":$N22}
          ]"

          echo "History Saved Successfully"
